### ISSUE TITLE
--privileged?

### ISSUE THREAD

**Issue by ghaering** [720kb/nginx-docker-container#3]
On the project page, you invoke the container with --privileged. There's no reason to do this, right?

**Comment by wouldgo** [comment]
Hi @ghaering,

there a specific reason for the `--privileged` run flag there. The need is in the device visibility in the container, due to the fact that the [`add-folder.sh`](https://github.com/720kb/nginx-docker-container/blob/master/add-folder.sh) script mount a piece of the host fs inside the container.

At the time of the first attempt to do this kind of thing I thought this is the way to achieve the goal. If you know a better solution feel free to contribute!

Best regards
Dario

**Comment by ghaering** [comment]
If all you want to do is have a folder from the host accessible, then this is the way to go:

https://docs.docker.com/engine/userguide/containers/dockervolumes/

"Mount a host directory as a data volume"

Plain simple Docker host mount.

**Comment by wouldgo** [comment]
One of my requirements is to not stop the already running container.  Declare a new volume, as far as I remember, means stops the running on and start over.

**Comment by wouldgo** [comment]
If there are some other issues related don't hesitate to reopen
